### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by RoelantStegmann** [mehmetboraezer/aws-lambda-unzip#1]
Could you maybe add the required permissions for the lambda function? :) 

An error occurred (403) when calling the HeadObject operation: Forbidden: ClientError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 37, in lambda_handler
s3.download_file(bucket, key, temp_file)
File "/var/runtime/boto3/s3/inject.py", line 130, in download_file
extra_args=ExtraArgs, callback=Callback)
File "/var/runtime/boto3/s3/transfer.py", line 307, in download_file
future.result()
File "/var/runtime/s3transfer/futures.py", line 73, in result
return self._coordinator.result()
File "/var/runtime/s3transfer/futures.py", line 233, in result
raise self._exception
File "/var/runtime/s3transfer/tasks.py", line 255, in _main
self._submit(transfer_future=transfer_future, **kwargs)
File "/var/runtime/s3transfer/download.py", line 353, in _submit
**transfer_future.meta.call_args.extra_args
File "/var/runtime/botocore/client.py", line 317, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 615, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by mehmetboraezer** [comment]
Hello @RoelantStegmann. Of course, I can add required permissions. I'll update this issue. Thank you for feedback. :)
